version: 0.2

phases:
  build:
    commands:
      - echo Entered Build phase stage
      - mvn clean package
  post_build:
    commands:
      - echo build completed successfully
artifacts:
  files:
    - target/create-order-service.jar
  discard-paths: yes